variables:
  LLNL_SLURM_SCHEDULER_PARAMETERS: "--nodes=1 -p pdebug --userns"
  QUAY_HOST: "quay.apps.czapps.llnl.gov"
  QUAY_ORG: "/exaworks/sdk-"
  QUAY_LATEST: "latest"

stages:
  - build
  - test
  - clean

Spack Build:
  stage: build
  tags:
    - nobatch
  needs: []
  script:
    - cd $HOME/
    - test -s $HOME/spack || git clone -c feature.manyFiles=true https://github.com/spack/spack.git
    - cd $HOME/spack && git pull && cd $HOME
    - . $HOME/spack/share/spack/setup-env.sh
    - spack install exaworks
    - spack install py-pytest


Spack Test:
  stage: test
  parallel:
      matrix:
        - TEST : ["rp", "swift-t", "parsl", "flux", "rp-flux", "parsl-flux"]
  before_script:
    - whoami
  tags:
    - batch
  needs: [Spack Build]
  variables:
    SCHEDULER_PARAMETERS: "-P CSC449 -nnodes 1 -W 30"
  script:
    - . $HOME/spack/share/spack/setup-env.sh
    - spack load exaworks py-pytest
    - export RADICAL_PILOT_DBURL="mongodb://am:W6gvSzpGBqAeuR4Z@95.217.193.116:27017/am"
    - bash ci/tests/${TEST}/test.sh
  after_script:
    - whoami


Spack Clean:
  stage: clean
  before_script:
    - whoami
  tags:
    - nobatch
  needs: [Spack Test]
  script:
    - rm -rf $HOME/spack/

