
stages:
  - build
  - test
  - clean

Spack Build:
  stage: build
  tags:
    - nobatch
  needs: []
  script:
    - cd $HOME/
    - rm -rf $HOME/spack $HOME/.spack
    - test -d $HOME/spack || git clone -c feature.manyFiles=true https://github.com/spack/spack.git $HOME/spack
    - cd $HOME/spack && git pull && cd $HOME
    - . $HOME/spack/share/spack/setup-env.sh
    - spack install exaworks
    - spack install py-pytest


Spack Test:
  stage: test
  parallel:
      matrix:
        - TEST : ["rp", "swift-t", "parsl", "flux", "rp-flux", "parsl-flux"]
  before_script:
    - whoami
  tags:
    - batch
  needs: [Spack Build]
  variables:
    SCHEDULER_PARAMETERS: "-P CSC449 -nnodes 1 -W 30"
    all_proxy: "socks://proxy.ccs.ornl.gov:3128/"
    ftp_proxy: "ftp://proxy.ccs.ornl.gov:3128/"
    http_proxy: "http://proxy.ccs.ornl.gov:3128/"
    https_proxy: "https://proxy.ccs.ornl.gov:3128/"
    no_proxy: "'localhost,127.0.0.0/8,*.ccs.ornl.gov,*.ncrc.gov',*.olcf.ornl.gov"
    CUSTOM_CI_BUILDS_DIR: "/gpfs/wolf/proj-shared/stf007/ci/${CI_JOB_ID}"

  script:
    - . $HOME/spack/share/spack/setup-env.sh
    - spack load exaworks py-pytest
    - bash ci/tests/${TEST}/test.sh
  after_script:
    - whoami


Spack Clean:
  stage: clean
  before_script:
    - whoami
  tags:
    - nobatch
  needs: [Spack Test]
  script:
    - rm -rf $HOME/spack/

