name: CI Test
on:
  pull_request:
  push: { branches: [master] }

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dockerbase: ["centos7", "centos8"]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Build docker images (base - ${{ matrix.dockerbase }})
      run: |
        docker build \
          -t exaworks/sdk-base:${{ matrix.dockerbase }} \
          --cache-from exaworks/sdk-base:${{ matrix.dockerbase }} \
          docker/base/${{ matrix.dockerbase }}
        docker build \
          -t rp:${{ matrix.dockerbase }} \
          --build-arg BASE_IMAGE=exaworks/sdk-base:${{ matrix.dockerbase }} \
          docker/rp
        docker build \
          -t rp_parsl:${{ matrix.dockerbase }} \
          --build-arg BASE_IMAGE=rp:${{ matrix.dockerbase }} \
          docker/Parsl
        docker build \
          -t rp_parsl_swift:${{ matrix.dockerbase }} \
          --build-arg BASE_IMAGE=rp_parsl:${{ matrix.dockerbase }} \
          docker/swift-t
        docker build \
          -t rp_parsl_swift_flux:${{ matrix.dockerbase }} \
          --build-arg BASE_IMAGE=rp_parsl_swift:${{ matrix.dockerbase }} \
          docker/flux

    - name: Run tests (base - ${{ matrix.dockerbase }})
      run: |
        docker run rp:${{ matrix.dockerbase }}
        ret_rp=$?
        echo "rp   : $ret_rp"
        # docker run flux:${{ matrix.dockerbase }}
        ret_flux=$?
        echo "flux : $ret_flux"
        # docker run swift-t:${{ matrix.dockerbase }}
        ret_swift=$?
        echo "swift: $ret_swift"
        # docker run parsl:${{ matrix.dockerbase }}
        ret_parsl=$?
        echo "parsl: $ret_parsl"
        echo "exit : $(expr $ret_rp + $ret_flux + $ret_swift + $ret_parsl)"
        exit $(expr $ret_rp + $ret_flux + $ret_swift + $ret_parsl)
        # docker run rp_parsl:${{ matrix.dockerbase }}
        # docker run rp_parsl_swift:${{ matrix.dockerbase }}
        # docker run rp_parsl_swift_flux:${{ matrix.dockerbase }}

  check-pr:
    name: validate commits
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
    - run: git fetch origin master
    - uses: exaworks/pr-validator@master
